Updated lint scripts

diff --git a/.github/workflows/Lint.yml b/.github/workflows/Lint.yml
--- a/.github/workflows/Lint.yml
+++ b/.github/workflows/Lint.yml
@@ -1,7 +1,15 @@
-name: PSScriptAnalyzer
+name: Lint
 
 on:
   workflow_dispatch:
+  push:
+    branches:
+      - master
+    # tags:
+    # - '*.*.*'
+  pull_request:
+    branches:
+      - master
 
 jobs:
   patch:
@@ -13,10 +21,10 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@main
 
-      - name: Run PSScriptAnalyzer
+      - name: Run Lint
         run: |
           # Check module for errors
-          $Results = @(Get-ChildItem -Path src -File -Recurse -Include *.ps1, *.psm1, *.psd1 | Invoke-ScriptAnalyzer)
+          $Results = @(Get-ChildItem -Path src -File -Recurse -Include *.ps1, *.psm1 | Invoke-ScriptAnalyzer)
           if ($Results | Where-Object -FilterScript {($_.Severity -eq "Error") -or ($_.Severity -eq "ParseError")})
           {
             Write-Verbose -Message "Found script issue" -Verbose
@@ -29,7 +37,8 @@ jobs:
               }
             } | Format-Table -AutoSize -Wrap
 
-            exit 1  # Exit with a non-zero status to fail the job
+            # Exit with a non-zero status to fail the job
+            exit 1
           }
 
       - name: Check JSONs validity
@@ -44,5 +53,36 @@ jobs:
           if (-not $JSONs)
           {
             Write-Verbose -Message "Found JSON issue" -Verbose
-            exit 1  # Exit with a non-zero status to fail the job
+            # Exit with a non-zero status to fail the job
+            exit 1
+          }
+
+      - name: Check module localizations
+        run: |
+          function Parse-PSD1
+          {
+            [CmdletBinding()]
+            param
+            (
+              [Microsoft.PowerShell.DesiredStateConfiguration.ArgumentToConfigurationDataTransformation()]
+              [hashtable]
+              $Path
+            )
+
+            return $Path
+          }
+
+          Get-ChildItem -Path src -File -Filter *.psd1 -Recurse | ForEach-Object -Process {
+              $File = $_.FullName
+
+              try
+              {
+                  Parse-PSD1 -Path $_.FullName -ErrorAction Stop | Out-Null
+              }
+              catch
+              {
+                  Write-Verbose -Message $File -Verbose
+                  # Exit with a non-zero status to fail the job
+                  exit 1
+              }
           }
