Fixed unnecessary localization strings

diff --git a/.github/workflows/Lint.yml b/.github/workflows/Lint.yml
--- a/.github/workflows/Lint.yml
+++ b/.github/workflows/Lint.yml
@@ -21,7 +21,7 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@main
 
-      - name: Run Lint
+      - name: PowerShell ScriptAnalyzer
         run: |
           # Check module for errors
           $Results = @(Get-ChildItem -Path src -File -Recurse -Include *.ps1, *.psm1 | Invoke-ScriptAnalyzer)
@@ -41,7 +41,7 @@ jobs:
             exit 1
           }
 
-      - name: Check JSONs validity
+      - name: JSONs validity
         run: |
           # Check JSONs for errors
           $JSONs = [Array]::TrueForAll((@(Get-ChildItem -Path Wrapper -File -Recurse -Filter *.json).FullName),
@@ -57,7 +57,7 @@ jobs:
             exit 1
           }
 
-      - name: Check module localizations
+      - name: psd1 validity
         run: |
           function Parse-PSD1
           {
@@ -84,5 +84,31 @@ jobs:
                   Write-Verbose -Message $File -Verbose
                   # Exit with a non-zero status to fail the job
                   exit 1
+              }
+          }
+  
+      - name: Localizations integrity
+        run: |
+          foreach ($Folder in @(Get-ChildItem -Path src -Directory))
+          {
+              Import-LocalizedData -BindingVariable Localization -UICulture $PSUICulture -BaseDirectory "$($Folder.FullName)\Module\Localizations" -FileName Sophia
+
+              foreach ($Key in $Localization.Keys)
+              {
+                  $Paths = @(
+                      "$($Folder.FullName)\Module\Sophia.psm1",
+                      "$($Folder.FullName)\Module\Private\InitialActions.ps1",
+                      "$($Folder.FullName)\Module\Private\PostActions.ps1",
+                      "$($Folder.FullName)\Module\Private\Set-UserShellFolder.ps1",
+                      "$($Folder.FullName)\Module\Private\Show-Menu.ps1",
+                      "$($Folder.FullName)\Import-TabCompletion.ps1"
+                  )
+
+                  if (-not ((Get-Content -Path $Paths -Raw) -match $Key))
+                  {
+                      Write-Verbose -Message "$Key was not found in $Folder.FullName folder" -Verbose
+                      # Exit with a non-zero status to fail the job
+                      exit 1
+                  }
               }
           }
